# Generated by Django 4.2.7 on 2024-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_category_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ImageField(upload_to='books/media/uploads/'),
        ),
    ]
