# Generated by Django 4.2.7 on 2024-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
