# Generated by Django 4.2.7 on 2024-02-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comments',
            new_name='Reviews',
        ),
    ]
