# Generated by Django 4.2.7 on 2024-02-15 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_review_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_by',
            field=models.ManyToManyField(blank=True, related_name='borrowed_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
