# Generated by Django 4.2.7 on 2024-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_borrowed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
