# Generated by Django 4.2.7 on 2024-02-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='returned',
        ),
    ]
