# Generated by Django 4.2.7 on 2024-02-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='balance_after_borrowing_book',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'RETURN_BOOK')], null=True),
        ),
    ]
