# Generated by Django 4.2.7 on 2024-02-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_borrow'),
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibraryaccount',
            name='borrows',
            field=models.ManyToManyField(related_name='borrowed_books', to='transactions.borrow'),
        ),
    ]
